# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
# relative_permalinks: true

# Setup

title:          "rickgray.me"
tagline:        "Quiet And Powerful"
description:    "Something Specail"
url:            "http://rickgray.me"
baseurl:        ""
paginate:       18
paginate_path:  "/page:num"

# Custom vars
friends:
    - name: "Purpleroc"
      url: "http://purpleroc.com"
      desc: "帅气学长"
    - name: "RicterZ"
      url: "http://ricter.me"
      desc: "萌学弟，最爱萝莉胖次"
    - name: "Caiji"
      url: "http://c-chicken.cc"
      desc: "小学弟弟，超级无数 (๑•̀ㅂ•́)و✧"
    - name: "MarginTop"
      url: "http://ujj.me"
      desc: "MarginTop大家都这么叫的 >>_|"
    - name: "君莫笑"
      url: "http://jmx-orz.cc"
      desc: "常用密码是laogong :D"
    - name: "ZeroLing"
      url: "http://zeroling.com"
      desc: "网校Ling神，前端牛"

author:
    name: "RickGray"
    url: "http://weibo.com/rickgray"
    email: "rickchen.vip@gmail.com"
    weibo: "http://weibo.com/rickgray"
    github: "https://github.com/RickGray"

disqus:
    shortname: "rickgrayblog"
    show: False


markdown: kramdown
