# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
# relative_permalinks: true


gems: [jekyll-paginate]


# Setup

title:          "rickgray.me"
tagline:        "Quiet And Powerful"
description:    "Something Specail"
url:            "http://rickgray.me"
baseurl:        ""
paginate:       20
paginate_path:  "/page:num"

# Custom vars
friends:
    - name: "Purpleroc"
      url: "http://purpleroc.com"
      desc: "帅气学长"
    - name: "RicterZ"
      url: "http://ricterz.me"
      desc: "萌学弟，最爱萝莉胖次"
    - name: "Caiji"
      url: "http://c-chicken.cc"
      desc: "小学弟弟，超级无数 (๑•̀ㅂ•́)و✧"
    - name: "君莫笑"
      url: "http://www.cnblogs.com/junmoxiao/"
      desc: "常用密码是laogong :D"
    - name: "ZeroLing"
      url: "http://zeroling.com"
      desc: "网校Ling神，前端牛"
    - name: "Dik1s"
      url: "http://z-onion.cc"
      desc: "喜欢带节奏别人的学弟"
    - name: "倩倩"
      url: "http://linqian.win"
      desc: "会敲代码的萌妹子"

author:
    name: "RickGray"
    url: "http://weibo.com/rickgray"
    email: "rickchen.vip@gmail.com"
    weibo: "http://weibo.com/rickgray"
    twitter: "http://twitter.com/R1ckGr3y"
    github: "https://github.com/RickGray"

disqus:
    shortname: "rickgrayblog"
    show: False


markdown: kramdown
