# Site Info
baseurl: ""
url: "http://rickgray.me"
banner: "{{ RickGray }}"


lang: "zh"
title: "Quiet And Powerful"
subtitle: "...and you?"

# Disqus settings
disqus:
    shortname: "rickgrayblog"
    show: True

# Author Info
author:
    name: "Chensy"
    email: "rickchen.vip@gmail.com"
    weibo: "http://weibo.com/rickgray"
    github: "https://github.com/RickGray"
