# Site Info
baseurl: ""
url: "http://rickgray.me"
banner: "{{ RickGray }}"

# Disqus settings
disqus:
    shortname: "rickgrayblog"

# Author Info
author:
    name: "Chensy"
    email: "rickchen.vip@gmail.com"
    weibo: "http://weibo.com/rickgray"
    github: "https://github.com/RickGray"
